transform: Compose
params:
  shuffle: True
  p: 1
  transforms:
    - transform: Gain
      params:
        p: 0.5
    - transform: AddColoredNoise
      params:
        p: 0.5
    - transform: ApplyImpulseResponse
      params:
        ir_paths: augmentation_files/ir/Audio
        p: 0.5
    - transform: SpliceOut
      params:
        p: 0.5