learning_rate: 
  default: 0.003
auto_lr_find:
  default: False
  help: Should the model find the learning rate? Overwrites learning rate
precision:
  default: 16
batch_size:
  default: 120
num_workers: 
  default: 12
val_check_interval: 
  default: 24
  help: default 200
gpus: 
  default: -1
  help: The number of GPUs to use, null indicate no GPUs
profiler: 
  default: null
  help: Should a profiler such as "simple" be set.
patience: 
  default: False
max_epochs: 
  default: 150
  help: Default 200
log_step:
  default: 100
  help: the log step of the model watch
watch:
  default: False
  help: Should wandb watch be activated?
default_root_dir:
  default: /work/wav2vec_finetune/baseline_models
config:
  default: null
  help: Additional config which overwrites the default configs
train_binary_models:
  default: False
train_multiclass_models:
  default: True
