learning_rate: 
  default: 0.00005
auto_lr_find:
  default: False
  help: Should the model find the learning rate? Overwrites learning rate
precision:
  default: 16
batch_size:
  default: 32
num_workers: 
  default: 30
check_val_every_n_epoch:
  default: 1
  help: validate every n epoch
gpus: 
  default: -1
  help: The number of GPUs to use, null indicate no GPUs
profiler: 
  default: null
  help: Should a profiler such as "simple" be set.
patience: 
  default: False
max_epochs: 
  default: 20
  help: Default 200
log_step:
  default: 1500
  help: the log step of the model watch
watch:
  default: False
  help: Should wandb watch be activated?
default_root_dir:
  default: /work/wav2vec_finetune/baseline_models_v3
config:
  default: null
  help: Additional config which overwrites the default configs
train_binary_models:
  default: True
train_multiclass_models:
  default: True
debug:
  default: False
augmentations:
  default: "configs/augmentation_config.yml"
use_weights: 
  default: True
  help: Use weights to account for unbalanced classes